Repository atbcb/usab-uswds, pull requests merged in 2020-08, with the labels that each got.

#129 Sarah prowag
  _prowag-shared-use/chapter-r1-application-and-administration.md
  _prowag-shared-use/chapter-r2-scoping-requirements.md
  _prowag-shared-use/chapter-r3-technical-requirements.md
Labels: clean up

#137 fixed table
  _prowag-shared-use/chapter-r4-supplementary-technical-requirements.md
Labels: clean up

#198 Ada sarah
  _pages/laws-ada.md
  _pages/laws-ra.md
Labels: clean up

#199 Update p-a11y.md
  _config.yml
  _pages/p-a11y.md
Labels: clean up

#196 Create readme.md for _pages
  _pages/readme.md
Labels: content

#226 Mde preamble sarah
  _mde/preamble.md
Labels: clean up, content
