Repository atbcb/usab-uswds, pull requests merged in 2020-09, with the labels that each got.

#378 Rsd board members
  504-contacts/index.html
  _ada-guides/chapter-10-swimming-pools-wading-pools-and-spas.md
  _config.yml
  _includes/meta.html
  admin/config.yml
  board-members/index.html
  index.html
Labels: bug, enhancement

#458 Philbratta edits
  _pages/p-iq.md
  _pages/p-plain.md
  _pages/p-privacy.md
  _pages/p-shutdown.md
Labels: content

#535 Presley ab ufas
  _aba/about.md
  _ignore/ufas-wip.md
  _pages/guidelines-standards/ufas.md
Labels: clean up
